branches:
  only:
    - master

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - git config user.name "ssdoz2sk"
  - git config user.email "mybalance22@gmail.com"
  - git clone --branch dist https://github.com/ssdoz2sk/embeddedSystemFE.git dist

script:
  - npm test

after_success:
  - npm run build
  - cd dist
  - git add .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@github.com/ssdoz2sk/embeddedSystemFE.git dist:dist
